// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfYROxVHE_cO-MNWr-i-Pi_kwvhF20C8',
    appId: '1:367568054526:web:0191464808dda215851daf',
    messagingSenderId: '367568054526',
    projectId: 'chat-7af0f',
    authDomain: 'chat-7af0f.firebaseapp.com',
    storageBucket: 'chat-7af0f.appspot.com',
    measurementId: 'G-7DP62G5NKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1RzCpvA2m-1Cjz2hRMmSB-9iCgGccS0',
    appId: '1:367568054526:android:e051205c9e7e4060851daf',
    messagingSenderId: '367568054526',
    projectId: 'chat-7af0f',
    storageBucket: 'chat-7af0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kMGUiwG9AEE2LNqYz1ugUwHM30tU4Vs',
    appId: '1:367568054526:ios:d630b5b7276bcad7851daf',
    messagingSenderId: '367568054526',
    projectId: 'chat-7af0f',
    storageBucket: 'chat-7af0f.appspot.com',
    iosClientId: '367568054526-d89sjg2ubpka03so2ovaouv33u6oq3d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kMGUiwG9AEE2LNqYz1ugUwHM30tU4Vs',
    appId: '1:367568054526:ios:d630b5b7276bcad7851daf',
    messagingSenderId: '367568054526',
    projectId: 'chat-7af0f',
    storageBucket: 'chat-7af0f.appspot.com',
    iosClientId: '367568054526-d89sjg2ubpka03so2ovaouv33u6oq3d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );
}
