// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM2ISFXt3cY2JaXE03_zSJqPNQlXkwQoI',
    appId: '1:229423124154:android:ee4815bd14796bee0d3c83',
    messagingSenderId: '229423124154',
    projectId: 'food-eb3c5',
    storageBucket: 'food-eb3c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2GQqi57o3o594rySoS-LMhKs3shF2mc',
    appId: '1:229423124154:ios:25521eab8a27ebdf0d3c83',
    messagingSenderId: '229423124154',
    projectId: 'food-eb3c5',
    storageBucket: 'food-eb3c5.appspot.com',
    iosClientId: '229423124154-grj4rab1b9iq3avqpc95o7si6jn5rd4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2GQqi57o3o594rySoS-LMhKs3shF2mc',
    appId: '1:229423124154:ios:25521eab8a27ebdf0d3c83',
    messagingSenderId: '229423124154',
    projectId: 'food-eb3c5',
    storageBucket: 'food-eb3c5.appspot.com',
    iosClientId: '229423124154-grj4rab1b9iq3avqpc95o7si6jn5rd4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );
}
